if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval $(dbus-launch --exit-with-session --sh-syntax)
fi
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment > /dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi

xrdb ${XDG_CONFIG_HOME}/xorg/xresources
xrandr --output DP-0 --mode 1920x1080 --rate 144 --left-of --output HDMI-0
exec ${XDG_CONFIG_HOME}/xorg/xsession
